/* ============================================================
   LUGʻAT. Yangi soʻz qoʻshish uchun shu roʻyxatga qator qoʻshing:
   ["lotincha", "grammatika (boʻlmasa boʻsh qoldiring)", "oʻzbekcha"],
   ============================================================ */
const WORDS = [
  ["abdomen", "", "qorin"],
  ["accessorius", "", "qoʻshimcha"],
  ["acromialis", "", "akromionga oid"],
  ["acromion", "", "akromion, yelka oʻsigʻi"],
  ["aer", "", "havo"],
  ["ala", "ae f", "qanot"],
  ["alveolus", "i m", "alveola"],
  ["ampulla", "", "ampula"],
  ["angulus", "i m", "burchak"],
  ["anterior", "", "oldingi"],
  ["aorta", "ae f", "aorta"],
  ["aponeurosis", "", "aponevroz (serbar pay)"],
  ["apertura", "", "apertura, teshik"],
  ["arcus", "us m", "yoy"],
  ["arteria", "ae f", "arteriya"],
  ["articularis", "", "boʻgʻimga oid"],
  ["articulatio", "", "boʻgʻim"],
  ["atlas", "", "I boʻyin umurtqasi"],
  ["auricula", "", "quloq suprasi (chigʻanogʻi)"],
  ["auricularis", "", "quloqqa oid"],
  ["auris", "", "quloq"],
  ["axis", "", "oʻq, II boʻyin umurtqasi"],
  ["basis cranii", "", "kalla suyagi asosi"],
  ["biceps", "", "ikki boshli"],
  ["brachialis", "", "yelkaga oid"],
  ["brachium", "i n", "yelka"],
  ["bucca", "ae f", "lunj"],
  ["calcaneus", "i m", "tovon suyagi"],
  ["canalis", "", "kanal"],
  ["canalis hypoglossalis", "", "til osti kanali"],
  ["canalis palatinus major", "", "katta tanglay kanali"],
  ["caput", "itis n", "bosh; boshcha"],
  ["cartilago", "", "togʻay"],
  ["caudalis", "", "quyruqqa oid"],
  ["cavitas", "atis f", "boʻshliq"],
  ["cavitas (cavum) cranii", "", "kalla suyagi boʻshligʻi"],
  ["caecus", "", "koʻr"],
  ["cellula", "", "hujayra"],
  ["cerebrum", "", "bosh miya"],
  ["chiasma", "", "kesishma"],
  ["cingulum", "", "belbogʻ"],
  ["clavicula", "", "oʻmrov"],
  ["clavicularis", "", "oʻmrovga oid"],
  ["coccygeus", "", "dumgʻazaga oid"],
  ["coccyx", "", "dumgʻaza"],
  ["collum", "", "boʻyin"],
  ["concha", "ae f", "chigʻanoq"],
  ["cornu", "us n", "shox"],
  ["corpus", "oris n", "tana"],
  ["corpus vesicae felleae", "", "oʻt pufagining tanasi"],
  ["costa", "ae f", "qovurgʻa"],
  ["costae", "", "qovurgʻalar"],
  ["costalis", "", "qovurgʻaga oid"],
  ["cranium", "i n", "kalla suyagi"],
  ["crista", "ae f", "qirra"],
  ["cruciatus", "", "xochsimon (krest shaklidagi)"],
  ["crus", "cruris n", "oyoq (boldir)"],
  ["dens incisivus", "", "kesuvchi tish"],
  ["dexter", "", "oʻng"],
  ["digitus", "i m", "barmoq"],
  ["diploe", "", "yassi suyakning gʻovak qismi"],
  ["ductus", "us m", "oqim, yoʻl"],
  ["dyspnoe", "", "nafas qisishi"],
  ["enamelum", "i n", "tish emali"],
  ["externus", "", "tashqi"],
  ["extremitas", "", "yakunlovchi qism, uchi"],
  ["facies", "", "yuza"],
  ["femur", "", "son, son suyagi"],
  ["fibula", "", "kichik boldir suyagi"],
  ["fissura", "", "yoriq"],
  ["flexio", "", "bukik"],
  ["foramen", "", "teshik"],
  ["foramina nutricia", "", "oziqlantiruvchi teshiklar"],
  ["fornix", "", "gumbaz"],
  ["fossa", "", "chuqurcha (uzunroq shaklda)"],
  ["fossa infratemporalis", "", "chakka osti chuqurchasi"],
  ["fovea", "", "chuqurcha (yumaloq)"],
  ["frenulum", "i n", "yugancha"],
  ["frontalis", "", "peshonaga oid"],
  ["genu", "us n", "tizza"],
  ["gingiva", "ae f", "milk"],
  ["haema", "", "qon"],
  ["haematopoeticus", "", "qon ishlab chiqaruvchi"],
  ["hepar", "", "jigar"],
  ["hilus", "", "darvoza"],
  ["humerus", "i m", "yelka suyagi"],
  ["iater", "", "vrach"],
  ["iliacus", "", "yonbosh"],
  ["impressio", "", "botiqlik"],
  ["incisura", "ae f", "oʻyma"],
  ["index", "", "koʻrsatkich barmoq"],
  ["inferior", "", "pastki"],
  ["infraspinatus", "", "qirra osti"],
  ["infundibulum", "", "voronka"],
  ["insula", "", "orolcha"],
  ["internus", "", "ichki"],
  ["intestinum", "", "ichak"],
  ["jejunum", "", "och ichak"],
  ["jugularis", "", "boʻyinturuqqa oid"],
  ["jugum", "i n", "boʻrtiqlik"],
  ["junctura", "", "biriktiruv"],
  ["labium", "i n", "lab"],
  ["lamina", "ae f", "plastinka"],
  ["larynx", "", "hiqildoq"],
  ["ligamentum", "i n", "boylam"],
  ["linea", "ae f", "chiziq"],
  ["linea aspera", "", "gʻadir-budur chiziq"],
  ["lingua", "ae f", "til"],
  ["lingula", "ae f", "tilcha"],
  ["major", "", "katta"],
  ["mandibula", "ae f", "pastki jagʻ"],
  ["mandibularis", "", "pastki jagʻga oid"],
  ["manubrium", "i n", "dasta"],
  ["manubrium sterni", "", "toʻsh dastasi"],
  ["maxilla", "ae f", "yuqori jagʻ"],
  ["maxillaris", "", "yuqori jagʻga oid"],
  ["meatus", "us m", "yoʻl"],
  ["medialis", "", "medial"],
  ["medianus", "", "oʻrtancha"],
  ["medius", "", "oʻrta"],
  ["membrana", "", "parda"],
  ["membrum", "", "aʼzo, tana aʼzosi"],
  ["mesenterium", "", "meʼdaning oʻrta qismi"],
  ["mesogastrium", "", "qorinning oʻrta qismi"],
  ["minor", "", "kichik"],
  ["mucosus", "", "shilliq"],
  ["musculus", "i m", "mushak (muskul)"],
  ["nasolacrimalis", "", "koʻz yoshiga va burunga oid"],
  ["neurocranium", "", "miya chanogʻi"],
  ["occiput", "", "ensa"],
  ["oedema", "", "shish"],
  ["oesophagus", "", "qizilungach"],
  ["olecranon", "", "olekranon (tirsak suyagining oʻsimtasi)"],
  ["orbita", "ae f", "koʻz kosasi"],
  ["os", "ossis n", "suyak (koʻpligi: ossa — suyaklar)"],
  ["os coccygis", "", "dumgʻaza, dum suyagi"],
  ["os coxae", "", "tos suyagi"],
  ["os femoris", "", "son suyagi"],
  ["os sacrum", "", "dumgʻaza suyagi"],
  ["palma", "", "kaft"],
  ["papilla", "ae f", "soʻrgʻich"],
  ["paries inferior", "", "pastki devor"],
  ["pars", "", "qism"],
  ["pars petrosa", "", "toshsimon qism"],
  ["patella", "ae f", "tizza qopqogʻi"],
  ["periosteum", "", "suyak usti pardasi"],
  ["pharyngeus", "", "halqumga oid"],
  ["platysma", "", "boʻyinning teri osti muskuli"],
  ["pleura", "", "plevra (parda)"],
  ["plexus", "", "chigal, oʻrim"],
  ["posterior", "", "orqadagi"],
  ["processus", "", "oʻsimta"],
  ["processus styloideus", "", "bigizsimon oʻsimta"],
  ["profundus", "", "chuqur"],
  ["proximalis", "", "proksimal (tanaga yaqin)"],
  ["pseudomembrana", "", "soxta parda"],
  ["pulpa", "ae f", "pulpa, yumshoq toʻqima"],
  ["radialis", "", "bilak suyagiga oid"],
  ["radius", "i m", "bilak suyagi"],
  ["radix", "", "ildiz"],
  ["raphe", "es f", "chok (yumshoq toʻqimalar birikishi)"],
  ["regio", "", "soha"],
  ["regio glutaea", "", "dumba sohasi"],
  ["saccus lacrimalis", "", "koʻz yoshi qopchasi"],
  ["scapula", "ae f", "kurak"],
  ["scapularis", "", "kurakka oid"],
  ["segmentum", "", "segment"],
  ["septum", "i n", "toʻsiq"],
  ["septum nasi", "", "burun toʻsigʻi"],
  ["sigmoideus", "", "sigmasimon"],
  ["sinister", "", "chap"],
  ["sinus", "", "sinus"],
  ["skeleton", "", "skelet"],
  ["spina", "ae f", "oʻtkir qirra"],
  ["sternum", "i n", "toʻsh"],
  ["sulci palatini", "", "tanglay egatlari"],
  ["sulcus", "i m", "egat"],
  ["sulcus palatinus", "", "tanglay egati"],
  ["sulcus sinus transversi", "", "koʻndalang sinus egati"],
  ["superficialis", "", "yuzaki"],
  ["superior", "", "tepadagi (yuqori)"],
  ["sutura", "ae f", "chok (suyak choki)"],
  ["thoracicus", "", "koʻkrak qafasiga oid"],
  ["thorax", "", "koʻkrak qafasi"],
  ["tibia", "", "katta boldir suyagi"],
  ["transversus", "", "koʻndalang"],
  ["truncus", "", "gavda"],
  ["tuba", "ae f", "nay"],
  ["tuber", "", "doʻmboq"],
  ["tuberculum", "", "doʻmboqcha"],
  ["tuberculum majus", "", "katta doʻmboqcha"],
  ["tympanum", "i n", "nogʻora"],
  ["ulna", "ae f", "tirsak suyagi"],
  ["ulnaris", "", "tirsak suyagiga oid"],
  ["uropoeticus", "", "siydik ishlab chiqaruvchi"],
  ["uvula", "", "tilcha (kichik til)"],
  ["vena", "ae f", "vena"],
  ["vena azygos", "", "toq vena"],
  ["ventralis", "", "ventral"],
  ["vertebra", "ae f", "umurtqa"],
  ["vertebrae", "", "umurtqalar"],
  ["vertebrae cervicales", "", "boʻyin umurtqalari"],
  ["vertebrae sacrales", "", "dumgʻaza umurtqalari"],
  ["vertebralis", "", "umurtqaga oid"],
  ["zona orbicularis", "", "koʻz sohasi"],
  ["zygomaticus", "", "yonoqqa oid"],
];
